SATELLITE_CLASSES = {
    0: "background",
    1: "building",
    2: "road",
    3: "water",
    4: "barren_land",
    5: "forest",
    6: "agriculture",
    7: "other_land",
    8: "bridge",
    9: "border",
    10: "checkpost",
    11: "car",
    12: "ship",
    13: "solar_panel",
    14: "truck",
    15: "bus",
    16: "compound",
    17: "aircraft",
    18: "harbor",
    19: "container_crane",
     20: "storage_tank",
    21: "changed_area",
}
